Dinghy and compose

diff --git a/.aliases/work b/.aliases/work
--- a/.aliases/work
+++ b/.aliases/work
@@ -1,16 +1,13 @@
 
 # Directories
 alias mp="~/mediaos/mp"
-alias adm="~/mediaos/mp/admin"
-alias fre="~/mediaos/mp/frontend"
+alias mpe="~/mediaos/mp/edit"
+alias fre="~/mediaos/mp/fre"
 alias rv="~/mediaos/mp/rover"
 alias drm="~/mediaos/mp/doorman"
-alias hdm="~/mediaos/mp/frontend/themes/hdm"
-
-# Replace IP on vhost if different
-dvh () {
-	sudo sed -i '' -e 's/Define ip ([0-9.]+)/Define ip '"$(dip)"'/g' /private/etc/apache2/extra/httpd-vhosts.conf && sudo apachectl restart
-}
+alias hdm="~/mediaos/mp/fre/themes/hdm"
+alias ftb="~/mediaos/mp/feed-the-beast"
+alias mpb="~/mediaos/mp/mp-bower-assets"
 
 # Docker
 alias dbuild="./bin/docker/build"
@@ -21,32 +18,22 @@ alias dstop_redis="./bin/docker/stop_redis"
 alias dstop_postgres="./bin/docker/stop_postgres"
 alias dsetup="./bin/docker/setup"
 alias dshell="./bin/docker/shell"
-alias dup="dmsl && drm && drs && rv && drs && adm && drs && fre && drs"
-
-# Restart containers sequence
-drs () {
-	local db;
-	local set;
-	[[ -a ./bin/docker/stop_postgres ]] && db=postgres
-	[[ -a ./bin/docker/setup ]] && set=setup
-	dstop && [[ ! -z $db ]] && dstop_postgres || dstop_redis && dstart && [[ ! -z $set ]] && sleep 3 && dsetup || return true
-}
 
 # Codeception
 alias cpt="../vendor/bin/codecept build"
 alias crun="../vendor/bin/codecept run -vvv"
-alias ccov="../vendor/bin/codecept run -vvv --coverage --coverage-html && ocov"
+alias ccov="../vendor/bin/codecept run -vvv --coverage --coverage-html && sleep 3 && ocov"
 alias ocov="open -a 'Google Chrome' codeception/_output/coverage/index.html"
 
 # ngrok
 ngr () {
 	local port;
-	if [[ $1 == adm ]]; then
-		port=":8002"
+	if [[ $1 == mpe ]]; then
+		port=":32776"
 	elif [[ $1 == fre ]]; then
-		port=":8003"
+		port=":32772"
 	fi
-	[[ ! -z $port ]] && ngrok http $(dip)$port || echo "missing key [ adm/fre ]"
+	[[ ! -z $port ]] && ngrok http $(dip)$port || echo "missing key [ mpe/fre ]"
 }
 
 # Grunt
